cleanup unused

diff --git a/home/bin/cl b/home/bin/cl
--- a/home/bin/cl
+++ b/home/bin/cl
@@ -9,7 +9,7 @@ MAX_TOKENS="8192"
 TEMPERATURE="0.0"
 
 die() {
-	printf '%s: %s\n' "$(basename "$0")" "$1" >&2
+	echo "${0##*/}: $1" >&2
 	exit 1
 }
 
@@ -26,17 +26,16 @@ usage() {
 
 construct_messages() {
 	local messages='[]'
-	local stdin_prompt
-	local arg_prompt
+	local input
 
 	if [[ ! -t 0 ]]; then
-		stdin_prompt=$(jq -Rs '.' </dev/stdin)
-		messages=$(jq --argjson stdin "$stdin_prompt" '. += [{"type": "text", "text": $stdin}]' <<<"$messages")
+		input=$(jq -Rs '.' </dev/stdin)
+		messages=$(jq --argjson stdin "$input" '. += [{"type": "text", "text": $stdin}]' <<<"$messages")
 	fi
 
 	for arg in "$@"; do
-		arg_prompt=$(jq -Rs '.' <<<"$arg")
-		messages=$(jq --argjson arg "$arg_prompt" '. += [{"type": "text", "text": $arg}]' <<<"$messages")
+		input=$(jq -Rs '.' <<<"$arg")
+		messages=$(jq --argjson arg "$input" '. += [{"type": "text", "text": $arg}]' <<<"$messages")
 	done
 
 	jq -n --argjson messages "$messages" '[{"role": "user", "content": $messages}]'
@@ -46,25 +45,29 @@ create_payload() {
 	local messages="$1"
 	local system_prompt
 
-	system_prompt=$(printf 'Be concise in your answers. Provide code
-		blocks that are complete. Avoid numbered lists, summaries are
-		better. For any technical questions, assume the user has
-		general knowledge in the area.' | tr -s '\n\t' ' ')
+	system_prompt=$(
+		tr -s '\n' ' ' <<-'EOF' | xargs
+			Be concise in your answers. Provide code blocks that are
+			complete. Avoid numbered lists, summaries are better.
+			For any technical questions, assume the user has general
+			knowledge in the area.
+		EOF
+	)
 
 	jq -n \
 		--arg model "$MODEL" \
 		--argjson max_tokens "$MAX_TOKENS" \
 		--argjson temperature "$TEMPERATURE" \
 		--arg system_prompt "$system_prompt" \
-		--argjson messages "$messages" '
-	{
-	  model: $model,
-	  max_tokens: $max_tokens,
-	  temperature: $temperature,
-	  stream: true,
-	  system: $system_prompt,
-	  messages: $messages
-	}'
+		--argjson messages "$messages" \
+		'{
+		  model: $model,
+		  max_tokens: $max_tokens,
+		  temperature: $temperature,
+		  stream: true,
+		  system: $system_prompt,
+		  messages: $messages
+		}'
 }
 
 dry_run() {
@@ -93,18 +96,16 @@ call_api() {
 		-H "content-type: application/json" \
 		--data-binary @- <<<"$payload" |
 		while IFS= read -r line; do
-			case "$line" in
+			case $line in
 			data:*)
-				json_data="${line#data: }"
-				jq -j '.delta.text // empty' <<<"$json_data"
+				jq -j '.delta.text // empty' <<<"${line#data: }"
 				;;
 			event:\ error)
 				read -r error_data
-				error_message=$(jq -r '.error.message' <<<"${error_data#data: }")
-				die "API error: $error_message"
+				die "$(jq -r '.error.message' <<<"${error_data#data: }")"
 				;;
 			event:\ content_block_stop)
-				printf '\n'
+				echo
 				break
 				;;
 			esac
@@ -113,7 +114,7 @@ call_api() {
 }
 
 main() {
-	[[ -z $API_KEY ]] && die "ANTHROPIC_API_KEY is not set"
+	[[ -z $API_KEY ]] && die "ANTHROPIC_API_KEY not set"
 	[[ $# -eq 0 && -t 0 ]] && usage
 
 	case $1 in
@@ -122,11 +123,13 @@ main() {
 		;;
 	-d)
 		shift
+		local messages payload
 		messages=$(construct_messages "$@")
 		payload=$(create_payload "$messages")
 		dry_run "$payload"
 		;;
 	*)
+		local messages payload
 		messages=$(construct_messages "$@")
 		payload=$(create_payload "$messages")
 		call_api "$payload"
diff --git a/install/install-d2 b/install/install-d2
--- a/install/install-d2
+++ b/install/install-d2
@@ -7,72 +7,67 @@ set -e
 # Note that the downloaded tar file is not removed and can be found in either
 # ~/Downloads or /tmp.
 
-declare REPO_OWNER=terrastruct
-declare REPO_NAME=d2
-declare EXE_NAME=d2
-declare EXE_TARGETDIR="$HOME/.local/bin"
-declare MAN_NAME=d2.1
-declare MAN_TARGETDIR="$HOME/.local/share/man/man1"
-declare OS ARCH
+declare REPO=terrastruct/d2
+declare NAME_EXE=d2
+declare NAME_MAN=d2.1
+declare TARGETDIR_EXE="$HOME/.local/bin"
+declare TARGETDIR_MAN="$HOME/.local/share/man/man1"
+
+declare OS
+declare ARCH
 declare TEMPDIR
 
 die() {
-	echo "$@" >&2
+	printf '%s: %s\n' "${0##*/}" "$1" >&2
 	exit 1
 }
 
-init_os() {
-	OS=$(uname -s)
-	case $OS in
+determine_system() {
+	case $(uname -s) in
 	Linux*) OS=linux ;;
 	Darwin*) OS=macos ;;
-	MINGW* | MSYS*) OS=windows ;;
+	*) die "unsupported OS" ;;
 	esac
-}
 
-init_arch() {
-	ARCH=$(uname -m)
-	case $ARCH in
+	case $(uname -m) in
 	aarch64) ARCH=arm64 ;;
-	arm64) ARCH=arm64 ;;
 	x86_64) ARCH=amd64 ;;
+	*) die "unsupported architecture" ;;
 	esac
 }
 
 download() {
-	local url path
-	url=$(curl -sSL "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/releases/latest" |
-		jq -r '.assets[]
-			| select(.name | test("'"$OS"'.*'"$ARCH"'.*tar.gz$"; "i"))
-			| .browser_download_url') ||
-		die "unable to fetch download URL"
-	path="$([[ -d $HOME/Downloads ]] && echo "$HOME/Downloads" || echo /tmp)/${url##*/}"
-	curl -L "$url" -o "$path"
+	url=$(curl -sSL "https://api.github.com/repos/$REPO/releases/latest" |
+		jq -r --arg os "$OS" --arg arch "$ARCH" '
+			.assets[] |
+			select(.name | contains($os) and contains($arch) and endswith(".tar.gz")) |
+			.browser_download_url')
+
+	[[ -z $url ]] && die "error fetching download url"
+
+	path="$HOME/Downloads/${url##*/}"
+	mkdir -p "$HOME/Downloads"
+	curl -#Lo "$path" "$url"
+
+	TEMPDIR=$(mktemp -d)
+	trap 'rm -rf -- "$TEMPDIR"' EXIT
 	tar -xf "$path" -C "$TEMPDIR"
-	echo "downloaded $REPO_OWNER/$REPO_NAME to $path" >&2
+
+	printf '%s -> %s\n' "$REPO" "$path" >&2
 }
 
-install_exe() {
-	find "$TEMPDIR" -type f -name "$EXE_NAME" ! -path "*completion*" -exec mv -t "$EXE_TARGETDIR" {} +
-	chmod +x "$EXE_TARGETDIR/$EXE_NAME"
-	echo "installed $EXE_NAME to $EXE_TARGETDIR" >&2
+install() {
+	mkdir -p "$TARGETDIR_EXE"
+	find "$TEMPDIR" -type f -name "$NAME_EXE" -exec mv -t "$TARGETDIR_EXE" {} + ||
+		die "error moving executable"
+	printf '%s -> %s\n' "$NAME_EXE" "$TARGETDIR_EXE/$NAME_EXE" >&2
+
+	mkdir -p "$TARGETDIR_MAN"
+	find "$TEMPDIR" -type f -name "$NAME_MAN" -exec mv -t "$TARGETDIR_MAN" {} + ||
+		die "error moving man page"
+	printf '%s -> %s\n' "$NAME_MAN" "$TARGETDIR_MAN/$NAME_MAN" >&2
 }
 
-install_man() {
-	find "$TEMPDIR" -type f -name "$MAN_NAME" ! -path "*completion*" -exec mv -t "$MAN_TARGETDIR" {} +
-	chmod +x "$MAN_TARGETDIR/$MAN_NAME"
-	echo "installed $MAN_NAME to $EXE_TARGETDIR" >&2
-}
-
-TEMPDIR=$(mktemp -d)
-trap 'rm -rf -- "$TEMPDIR"' EXIT
-
-init_os
-init_arch
+determine_system
 download
-
-mkdir -p "$EXE_TARGETDIR"
-install_exe
-
-mkdir -p "$MAN_TARGETDIR"
-install_man
+install
diff --git a/install/install-go b/install/install-go
--- a/install/install-go
+++ b/install/install-go
@@ -4,81 +4,62 @@ set -e
 # Install latest release of Go from https://go.dev/dl to ~/.local without
 # requiring root access.
 #
-# Note that the downloaded tar file is not removed and can be found in
-# ~/Downloads.
+# Note that the downloaded tar file is not removed and can be found in $TMPDIR
+# or /tmp.
 
 declare REPO=go.dev/dl
+declare NAME=go
 declare TARGETDIR="$HOME/.local"
 declare OS
 declare ARCH
 declare TEMPDIR
 
 die() {
-	printf '%s: %s.\n' "$(basename "$0")" "$1" >&2
+	echo "${0##*/}: $1" >&2
 	exit 1
 }
 
 determine_system() {
-	OS=$(uname -s)
-	case $OS in
+	case $(uname -s) in
 	Linux*) OS=linux ;;
 	Darwin*) OS=darwin ;;
+	*) die "unsupported os" ;;
 	esac
 
-	ARCH=$(uname -m)
-	case $ARCH in
+	case $(uname -m) in
 	aarch64) ARCH=arm64 ;;
 	x86_64) ARCH=amd64 ;;
+	*) die "unsupported arch" ;;
 	esac
-}
-
-verify_checksum() {
-	local expected_sha
-	local actual_sha
-	expected_sha=$(curl -sSL "https://$REPO/?mode=json" |
-		jq -r '.[0].files[]
-			| select(.os == "'"$OS"'")
-			| select(.arch == "'"$ARCH"'")
-			| select(.filename | endswith(".tar.gz"))
-			| .sha256') ||
-		die "unable to fetch sha hash"
-	actual_sha=$(sha256sum "$1" | cut -d ' ' -f 1)
-	if [[ "$expected_sha" != "$actual_sha" ]]; then
-		printf 'sha checksum verification failed\n' >&2
-		printf 'expected: %s\n' "$expected_sha" >&2
-		printf 'actual: %s\n' "$actual_sha" >&2
-		return 1
-	fi
 }
 
 download() {
-	local url
-	local path
 	url="https://$REPO/$(curl -sSL "https://$REPO/?mode=json" |
 		jq -r '.[0].files[]
 			| select(.os == "'"$OS"'")
 			| select(.arch == "'"$ARCH"'")
 			| select(.filename | endswith(".tar.gz"))
-			| .filename')" ||
-		die "unable to fetch download url"
-	path="$HOME/Downloads/${url##*/}"
-	mkdir -p "$HOME/Downloads"
-	curl -# -L "$url" -o "$path"
-	verify_checksum "$path"
+			| .filename')"
+
+	[[ -z $url ]] && die "error fetching download url"
+
+	path=${TMPDIR:-/tmp}/${url##*/}
+	curl -#Lo "$path" "$url"
+
+	TEMPDIR=$(mktemp -d)
+	trap 'rm -rf -- "$TEMPDIR"' EXIT
 	tar -xf "$path" -C "$TEMPDIR"
-	printf '%s -> %s\n' "$REPO" "$path" >&2
+
+	echo "$REPO -> $path" >&2
 }
 
 install() {
 	mkdir -p "$TARGETDIR"
-	rm -rf "$TARGETDIR/go"
+	rm -rf "${TARGETDIR:?}/$NAME"
 
-	mv "$TEMPDIR/go" "$TARGETDIR"
-	printf 'go -> %s/go\n' "$TARGETDIR" >&2
+	mv "$TEMPDIR/$NAME" "$TARGETDIR"
+	echo "$NAME/ -> $TARGETDIR/$NAME/" >&2
 }
-
-TEMPDIR=$(mktemp -d)
-trap 'rm -rf -- "$TEMPDIR"' EXIT
 
 determine_system
 download
diff --git a/install/install-uv b/install/install-uv
--- a/install/install-uv
+++ b/install/install-uv
@@ -14,51 +14,52 @@ declare OS
 declare TEMPDIR
 
 die() {
-	printf '%s: %s.\n' "$(basename "$0")" "$1" >&2
+	echo "${0##*/}: $1" >&2
 	exit 1
 }
 
 determine_system() {
-	OS=$(uname -s)
-	case $OS in
+	case $(uname -s) in
 	Linux*) OS=unknown-linux-gnu ;;
 	Darwin*) OS=apple-darwin ;;
+	*) die "unsupported os" ;;
 	esac
 
-	ARCH=$(uname -m)
-	case $ARCH in
+	case $(uname -m) in
 	aarch64) ARCH=aarch64 ;;
 	x86_64) ARCH=x86_64 ;;
+	*) die "unsupported arch" ;;
 	esac
 }
 
 download() {
-	local url
-	local path
 	url=$(curl -sSL "https://api.github.com/repos/$REPO/releases/latest" |
-		jq -r '.assets[]
-			| select(.name | test("'"$ARCH"'.*'"$OS"'.*tar.gz$"; "i"))
-			| .browser_download_url') ||
-		die "unable to fetch download url"
-	path="$HOME/Downloads/${url##*/}"
-	mkdir -p "$HOME/Downloads"
-	curl -# -L "$url" -o "$path"
+		jq -r --arg os "$OS" --arg arch "$ARCH" '
+			.assets[] |
+			select(.name | contains($os) and contains($arch) and endswith(".tar.gz")) |
+			.browser_download_url')
+
+	[[ -z $url ]] && die "error fetching download url"
+
+	path=${TMPDIR:-/tmp}/${url##*/}
+	curl -#Lo "$path" "$url"
+
+	TEMPDIR=$(mktemp -d)
+	trap 'rm -rf -- "$TEMPDIR"' EXIT
 	tar -xf "$path" -C "$TEMPDIR"
-	printf 'github.com/%s -> %s\n' "$REPO" "$path" >&2
+
+	echo "$REPO -> $path" >&2
 }
 
 install() {
 	mkdir -p "$TARGETDIR"
 
 	mv "$TEMPDIR/uv-$ARCH-$OS/uv" "$TARGETDIR"
-	printf 'uv -> %s/uv\n' "$TARGETDIR" >&2
+	echo "uv -> $TARGETDIR/uv" >&2
 
 	mv "$TEMPDIR/uv-$ARCH-$OS/uvx" "$TARGETDIR"
-	printf 'uvx -> %s/uvx\n' "$TARGETDIR" >&2
+	echo "uvx -> $TARGETDIR/uvx" >&2
 }
-
-TEMPDIR=$(mktemp -d)
-trap 'rm -rf -- "$TEMPDIR"' EXIT
 
 determine_system
 download
diff --git a/install/install-zig b/install/install-zig
--- a/install/install-zig
+++ b/install/install-zig
@@ -1,11 +1,11 @@
-#!/bin/bash -
+#!/bin/bash
 set -o nounset
 
 # Installs the latest nightly build of zig from https://ziglang.org/download to
 # ~/.local without requiring root access.
 #
-# Note that the downloaded tar file is not removed and can be found in either
-# ~/Downloads or /tmp.
+# Note that the downloaded tar file is not removed and can be found in $TMPDIR
+# or /tmp.
 
 declare REPO=ziglang.org/download
 declare NAME=zig
@@ -15,63 +15,51 @@ declare ARCH
 declare TEMPDIR
 
 die() {
-	printf '%s: %s.\n' "$(basename "$0")" "$1" >&2
+	echo "${0##*/}: $1" >&2
 	exit 1
 }
 
 determine_system() {
-	OS=$(uname -s)
-	case $OS in
+	case $(uname -s) in
 	Linux*) OS=linux ;;
 	Darwin*) OS=macos ;;
-	*) die "unsupported OS $OS" ;;
+	*) die "unsupported os $OS" ;;
 	esac
 
-	ARCH=$(uname -m)
-	case $ARCH in
+	case $(uname -m) in
 	aarch64) ARCH=aarch64 ;;
 	x86_64) ARCH=x86_64 ;;
 	*) die "unsupported arch $ARCH" ;;
 	esac
 }
 
-verify_checksum() {
-	local expected_checksum actual_checksum
-	expected_checksum=$(curl -sSL "https://$REPO/index.json" |
-		jq -r --arg arch "$ARCH" --arg os "$OS" '.master[$arch + "-" + $os].shasum') ||
-		die "Unable to fetch checksum"
-	actual_checksum=$(sha256sum "$1" | cut -d ' ' -f 1)
-	[[ $expected_checksum == "$actual_checksum" ]] ||
-		die "Checksum verification failed: expected $expected_checksum, got $actual_checksum"
-}
-
 download() {
-	local url path
 	url=$(curl -sSL "https://$REPO/index.json" |
-		jq -r --arg arch "$ARCH" --arg os "$OS" '.master[$arch + "-" + $os].tarball') ||
-		die "Unable to fetch download URL"
-	echo "$url"
-	path="$([[ -d $HOME/Downloads ]] && echo "$HOME/Downloads" || echo /tmp)/${url##*/}"
-	echo "$path"
-	curl -L "$url" -o "$path"
-	verify_checksum "$path"
+		jq -r --arg arch "$ARCH" --arg os "$OS" '
+			.master[$arch + "-" + $os].tarball')
+
+	[[ -z $url ]] && die "error fetching download url"
+
+	path=${TMPDIR:-/tmp}/${url##*/}
+	curl -#Lo "$path" "$url"
+
+	TEMPDIR=$(mktemp -d)
+	trap 'rm -rf -- "$TEMPDIR"' EXIT
 	tar -xf "$path" -C "$TEMPDIR"
-	echo "Downloaded tarball to $path" >&2
+
+	echo "$REPO -> $path" >&2
 }
 
 install() {
-	local dir
 	dir=$(find "$TEMPDIR" -mindepth 1 -maxdepth 1 -type d -print -quit)
-	mv "$dir" "$TARGETDIR/$NAME"
-	echo "Installed $NAME to $TARGETDIR" >&2
-}
 
-TEMPDIR=$(mktemp -d)
-trap 'rm -rf -- "$TEMPDIR"' EXIT
+	mkdir -p "$TARGETDIR"
+	rm -rf "${TARGETDIR:?}/$NAME"
+	mv "$dir" "$TARGETDIR/$NAME"
+
+	echo "$NAME/ -> $TARGETDIR/zig/" >&2
+}
 
 determine_system
 download
-
-mkdir -p "$TARGETDIR"
-rm -rf "${TARGETDIR:?}/$NAME"
 install
